# configs/constants.yaml
pv_name: "data-pv"
pvc_name: "data-pvc"
model_pv_name: "model-pv"
model_pvc_name: "model-pvc"
data_bucket: "data"
zenml_bucket: "zenml-data"
minio_storage_capacity: "200Gi"
model_storage_capacity: "100Gi"
ocr_model_storage_capcity: "4Gi"
storage_path: "/home/atharvaphatak/Desktop/minikube_path/minio"
model_storage_path: "/home/atharvaphatak/Desktop/models"
sql_host_path: "/home/atharva/Desktop/minikube_path/mysql"
minikube_cpus: 14
minikube_memory: "45g"
minikube_disk_size: "650GB"
minikube_addons: "ingress,metrics-server,nvidia-device-plugin"
minikube_gpus: "all"
infiscal_project_id: "c83b9229-4e69-4ed6-bd0d-797240c7904b"
minio_ingress_host: "minio-dharma.io"
minio_deployment_name: "minio-deployment"
minio_service_name: "minio-service"
